package patches.templates

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Template
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a template with id = 'NexusDockerLogin'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, Template({
    id("NexusDockerLogin")
    name = "Nexus Docker Login"
}))

